(function(){
  "use strict";
  const projects=[
    {id:"enterprise-order-management",index:"01",domain:"PLATFORM",tone:"#6ea8ff",title:"Enterprise Order Management",role:"Product strategy · orchestration",before:"Manually modeled paths",after:"Dependency-driven execution",contribution:"Led the shift to dependency-driven execution and a shared order contract across 19+ teams.",problem:"Every new service combination created more workflow modeling, deployment work and regression risk.",decision:"Move orchestration from predefined paths to capabilities that declare dependencies, while preserving existing service behavior during migration.",outcome:"Faster logic mapping with a scalable execution model and controlled migration risk.",proof:{type:"MEASURED",value:"20%",label:"Faster logic mapping",detail:"POC comparison of dependency-driven assembly versus manual workflow modeling."},tags:["Product goal","Architecture","Dependencies","Migration","19+ teams"],flow:["Product intent","Dependency graph","Readiness gate","Event execution","Provisioning"],flowCaption:"The platform assembles execution from declared capabilities and dependencies instead of manually modeled workflows.",board:{Frame:[["GOAL-01","Preserve behavior while changing the orchestration model","Constraint"],["RISK-02","Reduce regression exposure as combinations scale","Risk"]],Decide:[["DEC-01","Use capability dependencies instead of static paths","Architecture"],["DEC-02","Separate assessment from execution","Boundary"]],Ship:[["INC-01","Dependency foundation + shared order context","Foundation"],["INC-02","Scale, observability and policy controls","Scale"]]},metrics:[["Measured","20%","Faster mapping","POC comparison."],["Projected","75K/day","Target capacity","Architecture target, not production throughput."],["Actual scope","19+","Teams coordinated","Cross-team delivery scope."],["Actual scope","18","Service intents","Behavior preserved through migration."]]},
    {id:"rag-analysis-agent",index:"02",domain:"AI",tone:"#a78bfa",title:"Enterprise RAG Analysis Agent",role:"Product + engineering",before:"Manual investigation",after:"Grounded technical analysis",contribution:"Built the analysis agent and made citations, permission-aware retrieval and evaluation gates central to the product.",problem:"Complex failures took days of searching fragmented engineering knowledge and reconstructing relationships by hand.",decision:"Prioritize live source evidence, citations and grounding over conversational polish—and abstain when the evidence cannot support the answer.",outcome:"Investigations moved from roughly six days to about two hours with traceable evidence.",proof:{type:"MEASURED",value:"~6d → ~2h",label:"Investigation cycle",detail:"Historical troubleshooting compared with pilot use."},tags:["AI product","POC → pilot","Evaluation","Permissions","Architecture"],flow:["Live sources","Hybrid retrieval","Filter + rerank","Grounding gate","Cited answer"],flowCaption:"The chat is the final layer; the product value is current authorized evidence and a designed refusal path.",board:{Frame:[["GOAL-01","Reduce investigation time without trading away trust","Outcome"],["RISK-01","Unsupported answers are worse than no answer","Risk"]],Decide:[["DEC-01","Live connectors before broader UI polish","Priority"],["DEC-02","Golden evaluation set as a release gate","Quality"]],Ship:[["POC-01","Prove retrieval on difficult engineering artifacts","Discovery"],["PILOT-02","Citations, analyst pilot, then production connectors","Scale"]]},metrics:[["Measured","~6d → ~2h","Analysis cycle","End-to-end investigation comparison."],["Observed","11GB+","Knowledge corpus","Engineering evidence indexed."],["Observed","558+","Projects searchable","Cross-project scope."],["Evaluation","100% / 90%+","Groundedness / recall","25+ case golden set."]]},
    {id:"build-plus",index:"03",domain:"OPERATIONS",tone:"#54d6d6",title:"Build Plus",role:"Product ownership · supply chain",before:"Disconnected handoffs",after:"One governed asset lifecycle",contribution:"Established the part-data foundation and sequenced planning, fulfillment and recovery around a trusted item identity.",problem:"Master data, demand, fulfillment and reverse logistics were fragmented across systems and spreadsheets.",decision:"Create the governed item identity first, then use benefit/effort and ownership clarity to sequence the integrations that unlock downstream value.",outcome:"A connected lifecycle from part definition and demand planning through validated fulfillment, custody and recovery.",proof:{type:"IMPLEMENTED",value:"18 mo",label:"Rolling demand horizon",detail:"Consumption and regression-based planning capability."},tags:["LOB / LOE","RACI","Data governance","Supply chain","300+ requirements"],flow:["Item master","Demand plan","Procurement","Validation","Fulfillment","Custody + recovery"],flowCaption:"Trusted item identity is the anchor that lets planning, fulfillment, finance and recovery behave as one ecosystem.",board:{Frame:[["GOAL-01","Connect the full asset lifecycle around one trusted identity","Product goal"],["DEP-01","Master data must be reliable before downstream automation","Dependency"]],Decide:[["DEC-01","Use LOB / LOE to sequence integrations","Prioritization"],["DEC-02","Use RACI for reverse-logistics ownership","Ownership"]],Ship:[["INC-01","Master-data foundation + synchronization","Foundation"],["INC-02","Planning, fulfillment and lifecycle closure","Scale"]]},metrics:[["Measured baseline","50%+","MRO spreadsheet-managed","Before systemization."],["Implemented","18 mo","Demand horizon","Rolling planning capability."],["Projected","10,040","Hours / year","Program-level benefit."],["Actual scope","19","Handoffs addressed","Reverse-logistics complexity."]]},
    {id:"rfds",index:"04",domain:"ENGINEERING",tone:"#70d7ff",title:"RFDS Automation",role:"Product ownership · engineering automation",before:"Manual drafting",after:"Validated design generation",contribution:"Turned engineering judgment into testable rules, with source validation and a controlled path for urgent designs.",problem:"Manual drafting created stale configurations, equipment mismatches, version drift and field rework at national scale.",decision:"Treat the RFDS as an output of governed engineering data and rules, and block invalid combinations before generation.",outcome:"Generation dropped from hours to seconds while design-to-field exceptions fell below 5%.",proof:{type:"MEASURED",value:"$1.2M",label:"Annual cost avoidance",detail:"Labor avoided at production rollout volume."},tags:["Rules engine","Validation gates","Engineering UX","Operational scale","Measurement"],flow:["Planning data","Catalog data","Rules","Validation gate","RFDS + diagrams","Field execution"],flowCaption:"The durable product is the governed data-and-rules pipeline; the document is simply one generated output.",board:{Frame:[["GOAL-01","Generate a field-ready design from trusted data in seconds","Product goal"],["RISK-01","Free-form flexibility creates invalid configurations","Quality risk"]],Decide:[["DEC-01","Model engineering knowledge as governed rules","Product model"],["DEC-02","Validate source values before generation","Control"]],Ship:[["INC-01","Trusted source model + mappings","Foundation"],["INC-02","Automated design output + operational alignment","Scale"]]},metrics:[["Measured","$1.2M","Annual cost avoidance","Production rollout volume."],["Measured","2–4h → <30s","Generation time","Observed workflow."],["Measured","35–45% → <5%","Exception rate","Design-to-field rework."],["Observed","1,000+","Designs / month","Operating scale."]]},
    {id:"gl-coding",index:"05",domain:"FINANCE",tone:"#f4c66a",title:"Dynamic GL Coding",role:"Product ownership · financial systems",before:"Policy embedded in code",after:"Configurable financial routing",contribution:"Backed a foundational redesign and aligned project identity across operations, warehouse and ERP systems.",problem:"New portfolios could trigger months of engineering change because accounting policy lived in project-specific conditional logic.",decision:"Invest in reusable metadata-driven routing rather than add another fast branch of hard-coded logic.",outcome:"A reusable model adopted across 4+ portfolios with a 40% faster month-end close.",proof:{type:"MEASURED",value:"40%",label:"Faster month-end close",detail:"Post-implementation scenario analysis and reduced reconciliation effort."},tags:["Build vs extend","Platform thinking","Financial controls","Cross-system identity"],flow:["Project context","Common ID","Policy lookup","Validation","ERP posting","Audit evidence"],flowCaption:"Application architecture stays stable while approved financial policy evolves through governed configuration.",board:{Frame:[["GOAL-01","Let financial policy evolve without recurring redesign","Product goal"],["TENSION","Foundation investment versus another quick fix","Trade-off"]],Decide:[["DEC-01","Choose foundational redesign over one-off extension","Investment"],["DEC-02","Carry one project identity across systems","Architecture"]],Ship:[["INC-01","Common identity + configurable policy","Foundation"],["INC-02","Validation, reconciliation and evidence","Control"]]},metrics:[["Measured","40%","Faster close","Post-implementation result."],["Observed","4+","Portfolio adoption","Strategic portfolio types."],["Actual scope","3","Systems aligned","Operations, warehouse, ERP."],["Estimated","2–3mo → <1wk","Enablement","Supported-scenario estimate."]]},
    {id:"lease-vendor-management",index:"06",domain:"FINANCE",tone:"#ff8ba7",title:"Lease & Vendor Management",role:"Product ownership · lease-to-pay",before:"Payment workarounds",after:"Eligibility-gated lease-to-pay",contribution:"Defined payment eligibility controls and replaced the three-address vendor limit with a scalable model.",problem:"Fragmented lease data and vendor limits let invalid payment instructions surface only when Finance tried to execute them.",decision:"Move eligibility checks upstream and redesign the vendor-address model instead of extending recurring manual workarounds.",outcome:"A governed lease-to-pay lifecycle with scalable addresses, earlier validation and traceable financial controls.",proof:{type:"ACTUAL SCALE",value:"$23.7M/mo",label:"Rent roll governed",detail:"Recurring financial scale managed through the lease process."},tags:["Financial controls","RACI","Lifecycle product","Integration","Compliance"],flow:["Lease execution","Vendor data","Eligibility gate","Payment schedule","ERP","Reconciliation"],flowCaption:"Error detection moves from downstream Finance review to the point where lease and vendor data become eligible for payment.",board:{Frame:[["GOAL-01","Govern the lease obligation from execution to closeout","Product goal"],["RISK-01","Invalid vendor state creates recurring financial rework","Control risk"]],Decide:[["DEC-01","Validate vendor, address and IDs before approval","Control"],["DEC-02","Replace the three-address constraint","Platform"]],Ship:[["INC-01","Lease lifecycle + vendor scalability","Foundation"],["INC-02","Payment controls, GL/CIP and ERP evidence","Scale"]]},metrics:[["Actual scale","$23.7M/mo","Rent roll","Recurring obligations governed."],["Implemented","3 → scalable","Address model","Removed hard-coded limit."],["Estimated","~2x","Business-case ROI","Estimated operational return."],["Actual scope","~150","Stories delivered","Lease, vendor and controls scope."]]}
  ];

  let current=0;
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  function esc(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"})[c]);}

  function renderCards(){
    $("#project-stack").innerHTML=projects.map(p=>`<article class="project-card reveal" style="--tone:${p.tone}" data-card="${p.id}">
      <div class="card-top"><span>EPIC-${p.index}</span><b>${esc(p.domain)}</b></div>
      <h3>${esc(p.title)}</h3>
      <p class="shift">${esc(p.before)} <strong>→ ${esc(p.after)}</strong></p>
      <div class="card-proof"><div><span>${esc(p.proof.type)}</span><strong>${esc(p.proof.value)}</strong></div><button type="button" data-open="${p.id}" aria-label="Open ${esc(p.title)}">↗</button></div>
    </article>`).join("");
    bindOpen(); setupTilt(); setupReveal();
  }

  function lane(name,items,p){return `<div class="lane"><div class="lane-title"><span>${name}</span><b>${items.length}</b></div>${items.map(x=>`<article class="ticket" style="--tone:${p.tone}"><small>${esc(x[0])}</small><strong>${esc(x[1])}</strong><span>${esc(x[2])}</span></article>`).join("")}</div>`;}

  function populate(p){
    $("#case-id").textContent=`EPIC-${p.index}`; $("#case-domain").textContent=p.domain; $("#case-role").textContent=p.role; $("#case-title").textContent=p.title;
    $("#case-before").textContent=p.before; $("#case-after").textContent=p.after; $("#case-contribution").textContent=p.contribution;
    $("#case-tags").innerHTML=p.tags.map(t=>`<span>${esc(t)}</span>`).join("");
    $("#case-proof-type").textContent=p.proof.type; $("#case-proof-value").textContent=p.proof.value; $("#case-proof-label").textContent=p.proof.label; $("#case-proof-detail").textContent=p.proof.detail;
    $("#case-problem").textContent=p.problem; $("#case-decision").textContent=p.decision; $("#case-outcome").textContent=p.outcome; $("#flow-caption").textContent=p.flowCaption;
    $("#case-flow").innerHTML=p.flow.map((f,i)=>`<div class="flow-step"><span>0${i+1}</span><strong>${esc(f)}</strong></div>`).join("");
    $("#sprint-board").innerHTML=lane("Frame",p.board.Frame,p)+lane("Decide",p.board.Decide,p)+lane("Ship",p.board.Ship,p);
    $("#evidence-row").innerHTML=p.metrics.map(m=>`<article class="evidence-card"><span>${esc(m[0])}</span><strong>${esc(m[1])}</strong><h3>${esc(m[2])}</h3><p>${esc(m[3])}</p></article>`).join("");
    $("#next-title").textContent=projects[(current+1)%projects.length].title;
    $$(".case-view .reveal").forEach((el,i)=>{el.classList.remove("is-in");setTimeout(()=>el.classList.add("is-in"),40+i*65);});
  }

  function transition(fn){if(document.startViewTransition&&!matchMedia("(prefers-reduced-motion: reduce)").matches){document.startViewTransition(fn);}else fn();}
  function openProject(id){const i=projects.findIndex(p=>p.id===id);if(i<0)return;current=i;populate(projects[i]);transition(()=>{$("#home").hidden=true;$("#case").hidden=false;});history.replaceState(null,"",`#case/${id}`);scrollTo({top:0,behavior:"instant"});}
  function closeProject(){transition(()=>{$("#case").hidden=true;$("#home").hidden=false;});history.replaceState(null,"",location.pathname+location.search+"#work");setTimeout(()=>$("#work").scrollIntoView({block:"start"}),30);}
  function move(d){current=(current+d+projects.length)%projects.length;populate(projects[current]);history.replaceState(null,"",`#case/${projects[current].id}`);scrollTo({top:0,behavior:"smooth"});}
  function bindOpen(){$$("[data-open]").forEach(b=>{if(b.dataset.bound)return;b.dataset.bound="1";b.addEventListener("click",()=>openProject(b.dataset.open));});}

  function setupReveal(){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("is-in");io.unobserve(e.target);}}),{threshold:.12}); $$(".reveal:not(.is-in)").forEach(el=>io.observe(el));}
  function setupTilt(){$$("[data-card]").forEach(card=>{card.addEventListener("pointermove",e=>{if(matchMedia("(pointer:coarse)").matches)return;const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(700px) rotateX(${(-y*3.5).toFixed(2)}deg) rotateY(${(x*4).toFixed(2)}deg) translateY(-3px)`;});card.addEventListener("pointerleave",()=>card.style.transform="");});}

  function setupCanvas(){
    const c=$("#scene"),ctx=c.getContext("2d"),reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;if(reduced)return;
    let w,h,dpr,pts=[],mouse={x:-9999,y:-9999};
    function resize(){dpr=Math.min(devicePixelRatio||1,2);w=innerWidth;h=innerHeight;c.width=w*dpr;c.height=h*dpr;c.style.width=w+"px";c.style.height=h+"px";ctx.setTransform(dpr,0,0,dpr,0,0);const count=Math.min(95,Math.max(45,Math.round(w/17)));pts=Array.from({length:count},()=>({x:Math.random()*w,y:Math.random()*h,vx:(Math.random()-.5)*.14,vy:(Math.random()-.5)*.14,r:Math.random()*1.2+.45}));}
    addEventListener("resize",resize,{passive:true});addEventListener("pointermove",e=>{mouse.x=e.clientX;mouse.y=e.clientY;const s=$(".spotlight");s.style.left=e.clientX+"px";s.style.top=e.clientY+"px";},{passive:true});resize();
    function tick(){ctx.clearRect(0,0,w,h);for(const p of pts){p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>w)p.vx*=-1;if(p.y<0||p.y>h)p.vy*=-1;const dx=p.x-mouse.x,dy=p.y-mouse.y,md=Math.hypot(dx,dy);if(md<160&&md>1){p.x+=dx/md*.12;p.y+=dy/md*.12;}ctx.beginPath();ctx.fillStyle="rgba(150,182,230,.42)";ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill();}for(let i=0;i<pts.length;i++){for(let j=i+1;j<pts.length;j++){const a=pts[i],b=pts[j],d=Math.hypot(a.x-b.x,a.y-b.y);if(d<105){ctx.beginPath();ctx.strokeStyle=`rgba(108,145,205,${(1-d/105)*.085})`;ctx.lineWidth=.6;ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();}}}requestAnimationFrame(tick);}tick();
  }

  function setupMapParallax(){const map=$(".hero-map");if(!map)return;map.addEventListener("pointermove",e=>{if(matchMedia("(pointer:coarse)").matches)return;const r=map.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;$(".center-node").style.transform=`translate(-50%,-50%) translate(${x*8}px,${y*8}px)`;$$('.orbit-node',map).forEach((n,i)=>{n.style.marginLeft=(x*(i%2?5:-5))+"px";n.style.marginTop=(y*(i%2?-5:5))+"px";});});map.addEventListener("pointerleave",()=>{$(".center-node").style.transform="translate(-50%,-50%)";$$('.orbit-node',map).forEach(n=>{n.style.marginLeft="";n.style.marginTop="";});});}

  function setupCommand(){const d=$("#command"),inp=$("#command-input"),list=$("#command-list");function render(q=""){q=q.toLowerCase();const arr=projects.filter(p=>!q||p.title.toLowerCase().includes(q)||p.domain.toLowerCase().includes(q));list.innerHTML=arr.map(p=>`<button class="command-item" data-cmd-open="${p.id}"><span>${esc(p.title)}</span><small>${esc(p.domain)}</small></button>`).join("");$$('[data-cmd-open]',list).forEach(b=>b.addEventListener('click',()=>{d.close();openProject(b.dataset.cmdOpen);}));}$("[data-command]").addEventListener("click",()=>{render();d.showModal();setTimeout(()=>inp.focus(),20);});$("[data-close-command]").addEventListener("click",()=>d.close());inp.addEventListener("input",()=>render(inp.value));addEventListener("keydown",e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();render();d.showModal();setTimeout(()=>inp.focus(),20);}});}

  renderCards();bindOpen();setupReveal();setupCanvas();setupMapParallax();setupCommand();
  $("[data-back]").addEventListener("click",closeProject);$$('[data-next]').forEach(b=>b.addEventListener('click',()=>move(1)));$("[data-prev]").addEventListener("click",()=>move(-1));
  if(location.hash.startsWith("#case/"))setTimeout(()=>openProject(location.hash.slice(6)),0);
})();